### ISSUE TITLE
Add(or migrate) enum field for CapitalsDistances table 

### ISSUE THREAD

**Issue by bespilotnayakartoshka** [markevich/co2_offset#53]
https://www.postgresql.org/docs/9.1/datatype-enum.html 
1. add validation from current transport type(?) 
2.
2.1 current string field has to be migrated from simple string to PG ENUM TYPE 
or 
2.2 just add some checks to application level

**Comment by markevich** [comment]
https://github.com/gjaldon/ecto_enum#using-postgress-enum-type

**Comment by markevich** [comment]
Closed because we will no longer use distance types
